import type { ToolConfig } from "./toolTypes";

export const tools: ToolConfig[] = [
  {
    id: "merge",
    name: "Merge PDFs",
    description: "Combine PDFs in the order you choose.",
    category: "organize",
    acceptsMultipleFiles: true,
  },
  {
    id: "split",
    name: "Split PDF",
    description: "Extract a page range into a new PDF.",
    category: "organize",
    acceptsMultipleFiles: false,
    needsPageSelection: true,
  },
  {
    id: "remove-pages",
    name: "Remove Pages",
    description: "Delete selected pages from one PDF.",
    category: "organize",
    acceptsMultipleFiles: false,
    needsPageSelection: true,
  },
  {
    id: "reorder-pages",
    name: "Reorder Pages",
    description: "Arrange pages with a simple thumbnail workflow.",
    category: "organize",
    acceptsMultipleFiles: false,
    needsPageSelection: true,
  },
  {
    id: "images-to-pdf",
    name: "Images to PDF",
    description: "Turn JPG, PNG, or WebP files into a PDF.",
    category: "convert",
    acceptsMultipleFiles: true,
    acceptsImages: true,
  },
  {
    id: "encrypt",
    name: "Encrypt PDF",
    description: "Add password protection to a PDF.",
    category: "secure",
    acceptsMultipleFiles: false,
    needsPassword: true,
  },
  {
    id: "decrypt",
    name: "Decrypt PDF",
    description: "Unlock a PDF when you know the password.",
    category: "secure",
    acceptsMultipleFiles: false,
    needsPassword: true,
  },
  {
    id: "compress",
    name: "Compress PDF",
    description: "Reduce file size with lightweight optimization.",
    category: "optimize",
    acceptsMultipleFiles: false,
  },
  {
    id: "rotate",
    name: "Rotate Pages",
    description: "Rotate selected pages clockwise or counterclockwise.",
    category: "organize",
    acceptsMultipleFiles: false,
    needsPageSelection: true,
  },
];
